name: mobx_system
version: 1.0.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  mobx: ^1.2.1+4
  flutter_mobx: ^1.1.0+2
  meta: ^1.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: any
  build_runner: ^1.10.6
  mobx_codegen: ^1.1.2
